global:
  check_interval: 1m
  log_level: info
  socket_lxd: /var/snap/lxd/common/lxd/unix.socket
  socket_docker: /var/run/docker.sock
  push_gw: http://retro:9091
  addr: :9090

monitors:

  - name: WeeWX
    max_age: 5m
    type: lxd
    container_name: weewx
    label_name: job
    label_value: weewx
    restart_type: command
    restart_command:
      - /bin/systemctl
      - restart
      - weewx

  - name: API Exporter
    max_age: 1h30m
    type: docker
    container_name: prom-stack_api-exporter_1
    label_name: job
    label_value: api_exporter
    restart_type: container
