version: "3"
services:
  pushgw_bouncer:
    network_mode: bridge
    image: image.libretechconsulting.com/dev/pushgw_bouncer:latest
    container_name: pushgw_bouncer
    ports:
      - 9090:9090
    volumes:
      - /var/snap/lxd/common/lxd/unix.socket:/var/snap/lxd/common/lxd/unix.socket
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yml:/config.yml
    command:
      - --logLevel=debug
      - --checkInterval=5m
      - --configFile=/config.yml
      - --addr=:9090
    restart: unless-stopped
